### ISSUE TITLE
I get an error every single time it checks

### ISSUE THREAD

**Issue by FlipfudgeV2** [useragents/Proxyless-TikTok-Username-Checker#36]
[Unavailable] TxXO
Exception in thread Thread-67 (thread_starter):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Proxyless-TikTok-Username-Checker/main.py", line 96, in thread_starter
    self.check_username(self.usernames[self.counter])
  File "/root/Proxyless-TikTok-Username-Checker/main.py", line 67, in check_username
    self.update_title()
  File "/root/Proxyless-TikTok-Username-Checker/main.py", line 34, in update_title
    ctypes.windll.kernel32.SetConsoleTitleW(
AttributeError: module 'ctypes' has no attribute 'windll'
       [Unavailable] vtT6
Exception in thread Thread-68 (thread_starter):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Proxyless-TikTok-Username-Checker/main.py", line 96, in thread_starter
    self.check_username(self.usernames[self.counter])
  File "/root/Proxyless-TikTok-Username-Checker/main.py", line 67, in check_username
    self.update_title()
  File "/root/Proxyless-TikTok-Username-Checker/main.py", line 34, in update_title
    ctypes.windll.kernel32.SetConsoleTitleW(
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by ArticsGorrila** [comment]
same

**Comment by useragents** [comment]
Already answered [here](https://github.com/useragents/Proxyless-TikTok-Username-Checker/issues/16#issuecomment-1100086967).
